<?php

return [
    'severity' => ['error' => 'Error', 'warning' => 'Warning', 'notice' => 'Notice'],
    'title' => 'Accessibility Report',
    'summary' => 'Summary',
    'score' => 'Compliance score',
    'grade' => 'Grade',
    'total_issues' => 'Total issues',
    'errors' => 'Errors',
    'warnings' => 'Warnings',
    'notices' => 'Notices',
    'no_issues' => 'No accessibility issues found.',
    'element' => 'Element',
    'suggestion' => 'Suggestion',
    'rule' => 'WCAG',
    'generated_by' => 'Generated by laravel-bfsg :version on :date',
    'url' => 'URL',
    'issues_found' => ':count issues found',
];
